import { GLOBAL_TYPES } from "./global.types";

export const PHOTO_TYPES = {
    PHOTOS_FETCHED: "PHOTOS_FETCHED",
    PHOTOS_UPLOADED: "PHOTOS_UPLOADED",
    DELETE_UPLOADED_PHOTO: "DELETE_UPLOADED_PHOTO",
    UPDATE_UPLOADED_PHOTO: "UPDATE_UPLOADED_PHOTO",
  };